In [8]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [7]:
"""
Author: Ashyam Zubair
Created Date: 14-02-2019
"""
import json
import pandas as pd
import traceback
import sqlalchemy
import os

from MySQLdb._exceptions import OperationalError
from sqlalchemy import create_engine, exc
from time import time

# try:
#     from app.ace_logger import Logging
# except:
#     from ace_logger import Logging
     
# logging = Logging()

import logging
class DB(object):
    def __init__(self, database, host='127.0.0.1', user='root', password='', port='3306', tenant_id=None):
        """
        Initialization of databse object.

        Args:
            databse (str): The database to connect to.
            host (str): Host IP address. For dockerized app, it is the name of
                the service set in the compose file.
            user (str): Username of MySQL server. (default = 'root')
            password (str): Password of MySQL server. For dockerized app, the
                password is set in the compose file. (default = '')
            port (str): Port number for MySQL. For dockerized app, the port that
                is mapped in the compose file. (default = '3306')
        """

        if host in ["common_db","extraction_db", "queue_db", "template_db", "table_db", "stats_db", "business_rules_db", "reports_db"]:
            self.HOST = os.environ['HOST_IP']
            self.USER = 'root'
            self.PASSWORD = os.environ['LOCAL_DB_PASSWORD']
            self.PORT = '3306'
            self.DATABASE = f'{tenant_id}_{database}' if tenant_id is not None and tenant_id else database
        else:
            self.HOST = host
            self.USER = user
            self.PASSWORD = password
            self.PORT = port
            self.DATABASE = f'{tenant_id}_{database}' if tenant_id is not None and tenant_id else database
        
        logging.info(f'Host: {self.HOST}')
        logging.info(f'User: {self.USER}')
        logging.info(f'Password: {self.PASSWORD}')
        logging.info(f'Port: {self.PORT}')
        logging.info(f'Database: {self.DATABASE}')

        self.connect()

    def connect(self, max_retry=5):
        retry = 1

        try:
            start = time()
            logging.debug(f'Making connection to `{self.DATABASE}`...')
            config = f'mysql://{self.USER}:{self.PASSWORD}@{self.HOST}:{self.PORT}/{self.DATABASE}?charset=utf8'
            self.db_ = create_engine(config, connect_args={'connect_timeout': 2}, pool_recycle=300)
            logging.info(f'Engine created for `{self.DATABASE}`')
            while retry <= max_retry:
                try:
                    self.engine = self.db_.connect()
                    logging.info(f'Connection established succesfully to `{self.DATABASE}`! ({round(time() - start, 2)} secs to connect)')
                    break
                except Exception as e:
                    logging.warning(f'Connection failed. Retrying... ({retry}) [{e}]')
                    retry += 1
                    self.db_.dispose()
        except:
            logging.exception(f'Something went wrong while connecting. Check trace.')
            return

    def execute(self, query, database=None, **kwargs):
        """
        Executes an SQL query.

        Args:
            query (str): The query that needs to be executed.
            database (str): Name of the database to execute the query in. Leave
                it none if you want use database during object creation.
            params (list/tuple/dict): List of parameters to pass to in the query.

        Returns:
            (DataFrame) A pandas dataframe containing the data from the executed
            query. (None if an error occurs)
        """
        data = None

        # Use new database if a new databse is given
        if database is not None:
            try:
                config = f'mysql://{self.USER}:{self.PASSWORD}@{self.HOST}:{self.PORT}/{database}?charset=utf8'
                engine = create_engine(config, pool_recycle=300)
            except:
                logging.exception(f'Something went wrong while connecting. Check trace.')
                return False
        else:
            engine = self.engine

        try:
            logging.debug(f'Query: {query}')
            data = pd.read_sql(query, engine, index_col='id', **kwargs)
        except exc.ResourceClosedError:
            logging.warning('Query does not have any value to return.')
            return True
        except (exc.StatementError, OperationalError) as e:
            logging.warning(f'Creating new connection. Engine/Connection is probably None. [{e}]')
            self.connect()
            data = pd.read_sql(query, self.engine, index_col='id', **kwargs)
        except:
            logging.exception('Something went wrong executing query. Check trace.')
            params = kwargs['params'] if 'params' in kwargs else None
            return False

        return data.where((pd.notnull(data)), None)

    def execute_(self, query, database=None, **kwargs):
        """
        Executes an SQL query.

        Args:
            query (str): The query that needs to be executed.
            database (str): Name of the database to execute the query in. Leave
                it none if you want use database during object creation.
            params (list/tuple/dict): List of parameters to pass to in the query.

        Returns:
            (DataFrame) A pandas dataframe containing the data from the executed
            query. (None if an error occurs)
        """
        data = None

        # Use new database if a new databse is given
        if database is not None:
            try:
                config = f'mysql://{self.USER}:{self.PASSWORD}@{self.HOST}:{self.PORT}/{database}?charset=utf8'
                engine = create_engine(config, pool_recycle=300)
            except:
                logging.exception(f'Something went wrong while connecting. Check trace.')
                return False
        else:
            engine = self.engine

        try:
            data = pd.read_sql(query, engine, **kwargs)
        except exc.ResourceClosedError:
            return True
        except:
            logging.exception(f'Something went wrong while connecting. Check trace.')
            params = kwargs['params'] if 'params' in kwargs else None
            return False

        return data.replace({pd.np.nan: None})


    def insert(self, data, table, database=None, **kwargs):
        """
        Write records stored in a DataFrame to a SQL database.

        Args:
            data (DataFrame): The DataFrame that needs to be write to SQL database.
            table (str): The table in which the rcords should be written to.
            database (str): The database the table lies in. Leave it none if you
                want use database during object creation.
            kwargs: Keyword arguments for pandas to_sql function.
                See https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_sql.html
                to know the arguments that can be passed.

        Returns:
            (bool) True is succesfully inserted, else false.
        """
        logging.info(f'Inserting into `{table}`')

        # Use new database if a new databse is given
        if database is not None:
            try:
                config = f'mysql://{self.USER}:{self.PASSWORD}@{self.HOST}:{self.PORT}/{database}?charset=utf8'
                engine = create_engine(config, pool_recycle=300)
            except:
                logging.exception(f'Something went wrong while connecting. Check trace.')
                return False
        else:
            engine = self.engine

        try:
            data.to_sql(table, engine, **kwargs)
            try:
                self.execute(f'ALTER TABLE `{table}` ADD PRIMARY KEY (`id`);')
            except:
                pass
            return True
        except:
            logging.exception('Something went wrong inserting. Check trace.')
            return False

    def insert_dict(self, data, table):
        """
        Insert dictionary into a SQL database table.

        Args:
            data (DataFrame): The DataFrame that needs to be write to SQL database.
            table (str): The table in which the rcords should be written to.

        Returns:
            (bool) True is succesfully inserted, else false.
        """
        logging.info(f'Inserting dictionary data into `{table}`...')
        logging.debug(f'Data:\n{data}')

        try:
            column_names = []
            params = []

            for column_name, value in data.items():
                column_names.append(f'`{column_name}`')
                params.append(value)

            logging.debug(f'Column names: {column_names}')
            logging.debug(f'Params: {params}')

            columns_string = ', '.join(column_names)
            param_placeholders = ', '.join(['%s'] * len(column_names))

            query = f'INSERT INTO {table} ({columns_string}) VALUES ({param_placeholders})'

            return self.execute(query, params=params)
        except:
            logging.exception('Error inserting data.')
            return False

    def update(self, table, update=None, where=None, database=None, force_update=False):
        # Use new database if a new databse is given
        if database is not None:
            try:
                config = f'mysql://{self.USER}:{self.PASSWORD}@{self.HOST}:{self.PORT}/{database}?charset=utf8'
                self.engine = create_engine(config, pool_recycle=300)
            except:
                logging.exception(f'Something went wrong while connecting. Check trace.')
                return False

        logging.info(f'Updating table: `{table}`')
        logging.info(f'Update data: `{update}`')
        logging.info(f'Where clause data: `{where}`')
        logging.info(f'Force update flag: `{force_update}`')

        try:
            set_clause = []
            set_value_list = []
            where_clause = []
            where_value_list = []

            if where is not None and where:
                for set_column, set_value in update.items():
                    set_clause.append(f'`{set_column}`=%s')
                    set_value_list.append(set_value)
                set_clause_string = ', '.join(set_clause)
            else:
                logging.error(f'Update dictionary is None/empty. Must have some update clause.')
                return False

            if where is not None and where:
                for where_column, where_value in where.items():
                    where_clause.append(f'{where_column}=%s')
                    where_value_list.append(where_value)
                where_clause_string = ' AND '.join(where_clause)
                query = f'UPDATE `{table}` SET {set_clause_string} WHERE {where_clause_string}'
            else:
                if force_update:
                    query = f'UPDATE `{table}` SET {set_clause_string}'
                else:
                    message = 'Where dictionary is None/empty. If you want to force update every row, pass force_update as True.'
                    logging.error(message)
                    return False

            params = set_value_list + where_value_list
            self.execute(query, params=params)
            return True
        except:
            logging.exception('Something went wrong updating. Check trace.')
            return False

    def get_column_names(self, table, database=None):
        """
        Get all column names from an SQL table.

        Args:
            table (str): Name of the table from which column names should be extracted.
            database (str): Name of the database in which the table lies. Leave
                it none if you want use database during object creation.

        Returns:
            (list) List of headers. (None if an error occurs)
        """
        try:
            logging.info(f'Getting column names of table `{table}`')
            return list(self.execute(f'SELECT * FROM `{table}`', database))
        except:
            logging.exception('Something went wrong getting column names. Check trace.')
            return

    def execute_default_index(self, query, database=None, **kwargs):
        """
        Executes an SQL query.

        Args:
            query (str): The query that needs to be executed.
            database (str): Name of the database to execute the query in. Leave
                it none if you want use database during object creation.
            params (list/tuple/dict): List of parameters to pass to in the query.

        Returns:
            (DataFrame) A pandas dataframe containing the data from the executed
            query. (None if an error occurs)
        """
        data = None

        # Use new database if a new databse is given
        if database is not None:
            try:
                config = f'mysql://{self.USER}:{self.PASSWORD}@{self.HOST}:{self.PORT}/{database}?charset=utf8'
                engine = create_engine(config, pool_recycle=300)
            except:
                logging.exception(f'Something went wrong while connecting. Check trace.')
                return False
        else:
            engine = self.engine

        try:
            data = pd.read_sql(query, engine, **kwargs)
        except exc.ResourceClosedError:
            return True
        except:
            logging.exception(f'Something went wrong while executing query. Check trace.')
            params = kwargs['params'] if 'params' in kwargs else None
            return False

        return data.where((pd.notnull(data)), None)


    def get_all(self, table, database=None, discard=None):
        """
        Get all data from an SQL table.

        Args:
            table (str): Name of the table from which data should be extracted.
            database (str): Name of the database in which the table lies. Leave
                it none if you want use database during object creation.
            discard (list): columns to be excluded while selecting all
        Returns:
            (DataFrame) A pandas dataframe containing the data. (None if an error
            occurs)
        """
        logging.info(f'Getting all data from `{table}`')
        if discard:
            logging.info(f'Discarding columns `{discard}`')
            columns = list(self.execute_default_index(f'SHOW COLUMNS FROM `{table}`',database).Field)
            columns = [col for col in columns if col not in discard]
            columns_str = json.dumps(columns).replace("'",'`').replace('"','`')[1:-1]
            return self.execute(f'SELECT {columns_str} FROM `{table}`', database)

        return self.execute(f'SELECT * FROM `{table}`', database)

    def get_latest(self, data, group_by_col, sort_col):
        """
        Group data by a column containing repeated values and get latest from it by
        taking the latest value based on another column.

        Example:
        Get the latest products
            id     product   date
            220    6647     2014-09-01
            220    6647     2014-10-16
            826    3380     2014-11-11
            826    3380     2015-05-19
            901    4555     2014-09-01
            901    4555     2014-11-01

        The function will return
            id     product   date
            220    6647     2014-10-16
            826    3380     2015-05-19
            901    4555     2014-11-01

        Args:
            data (DataFrame): Pandas DataFrame to query on.
            group_by_col (str): Column containing repeated values.
            sort_col (str): Column to identify the latest record.

        Returns:
            (DataFrame) Contains the latest records. (None if an error occurs)
        """
        try:
            logging.info('Grouping data...')
            logging.info(f'Data: {data}')
            logging.info(f'Group by column: {group_by_col}')
            logging.info(f'Sort column: {sort_col}')
            return data.sort_values(sort_col).groupby(group_by_col).tail(1)
        except KeyError as e:
            logging.errot(f'Column `{e.args[0]}` does not exist.')
            return None
        except:
            logging.exception('Something went wrong while grouping data.')
            return None

In [6]:
import os
os.environ['HOST_IP'] = '3.208.195.34'
os.environ['LOCAL_DB_USER'] = 'root'
os.environ['LOCAL_DB_PASSWORD'] = 'AlgoTeam123'
os.environ['LOCAL_DB_PORT'] = '3306'

tenant_id = 'karvy'

db_config = {
    'host': os.environ['HOST_IP'],
    'user': os.environ['LOCAL_DB_USER'],
    'password': os.environ['LOCAL_DB_PASSWORD'],
    'port': os.environ['LOCAL_DB_PORT']
}

In [18]:
# %load apply_business_rule.py
# comment below two for local testing
# from ace_logger import Logging
# logging = Logging()
import pandas as pd
import ntpath

# uncomment these below lines for local testing
import logging 
logger=logging.getLogger() 
logger.setLevel(logging.DEBUG) 



import json
import os
# from db_utils import DB 

from BusinessRules import BusinessRules

# one configuration
db_config = {
    'host': os.environ['HOST_IP'],
    'user': os.environ['LOCAL_DB_USER'],
    'password': os.environ['LOCAL_DB_PASSWORD'],
    'port': os.environ['LOCAL_DB_PORT']
}


# give any path...platform independent...get the base name
def path_leaf(path):
    """give any path...platform independent...get the base name"""
    head, tail = ntpath.split(path)
    return tail or ntpath.basename(head)


def to_DT_data(parameters):
    """Amith's processing for parameters"""
    output = []
    try:
        for param_dict in parameters:
            print(param_dict)    
            if param_dict['column'] == 'Add_on_Table':
                output.append({'table': param_dict['table'],'column': param_dict['column'],'value': param_dict['value']})
                # Need to add a function to show this or tell Kamal check if its addon table and parse accordingly
            else:                
                output.append({'table': param_dict['table'],'column': param_dict['column'],'value': param_dict['value']})
    except:
        print("Error in to_DT_data()")
        traceback.print_exc()
        return []
    try:
        output = [dict(t) for t in {tuple(d.items()) for d in output}]
    except:
        print("Error in removing duplicate dictionaries in list")
        traceback.print_exc()
        pass
    return output

def get_data_sources(tenant_id, case_id, column_name, master=False):
    """Helper to get all the required table data for the businesss rules to apply
    """
    get_datasources_query = "SELECT * from `data_sources`"
    business_rules_db = DB('business_rules', tenant_id=tenant_id, **db_config)
    data_sources = business_rules_db.execute(get_datasources_query)


    # sources
    sources = json.loads(list(data_sources[column_name])[0])
    
    
    data = {}
    for database, tables in sources.items():
        db = DB(database, tenant_id=tenant_id, **db_config)
        for table in tables:
            if master:
                query = f"SELECT * from `{table}`"
                df = db.execute(query)
            else:
                query = f"SELECT * from `{table}` WHERE case_id = %s"
                params = [case_id]
                df = db.execute(query, params=params)
            if not df.empty:
                data[table] = df.to_dict(orient='records')[0]
            else:
                data[table] = {}
    
    
    case_id_based_sources = json.loads(list(data_sources['case_id_based'])[0])
    
    return data
                
def get_rules(tenant_id, group):
    """Get the rules based on the stage, tenant_id"""
    business_rules_db = DB('business_rules', tenant_id=tenant_id, **db_config)
    get_rules_query = "SELECT * from `sequence_rule_data` where `group` = %s"
    params = [group]
    rules = business_rules_db.execute(get_rules_query, params=params)
    return rules

def update_tables(case_id, tenant_id, updates):
    """Update the values in the database"""
    try:
        extraction_db = DB('extraction', tenant_id=tenant_id, **db_config) # only in ocr or process_queue we are updating
        queue_db = DB('queues', tenant_id=tenant_id, **db_config) # only in ocr or process_queue we are updating
        
        for table, colum_values in updates.items():
            if table == 'ocr':
                extraction_db.update(table, update=colum_values, where={'case_id':case_id})
            if table == 'process_queue':
                queue_db.update(table, update=colum_values, where={'case_id':case_id})
    except Exception as e:
        logging.error("Error in updating the tables")
        logging.error("check whether the table exists")
        logging.error(e)
        
    return "UPDATED IN THE DATABASE SUCCESSFULLY"


def writeToCsv(df, file_path, required_standard_mapping=None):
    """Write the dataframe to csv"""
    if not required_standard_mapping:
        required_standard_mapping = {ele:ele for ele in list(df.columns)}
    required_columns = required_standard_mapping.values()
    try:

        # first find whether any csv exists with the file_name
        existing_df = pd.read_csv(file_path)
        mode = 'a'
        headers = False
        df.to_csv(file_path, columns=required_columns, mode=mode, header=headers, index=False)
    except:
        # no sample file exists
        headers = True
        mode = 'w'
        
        # rename the columns in the dataframe to standardized columns            
        df = df.rename(columns=required_standard_mapping)
        df.to_csv(file_path, columns=required_columns, mode=mode, header=headers, index=False)
                
    return "Written to csv successfully"




# as of now run this...you can combine the run_chained_rules and column_chained rules with small changes
def run_chained_rules_column(file_path, chain_rules, start_rule_id=None):
    """Execute the chained rules column wise"""
    
    # get the mapping of the rules...basically a rule_id maps to a rule
    rule_id_mapping = {}
    for ind, rule in chain_rules.iterrows():
        rule_id_mapping[rule['rule_id']] = [rule['rule_string'], rule['next_if_sucess'], rule['next_if_failure'], rule['stage'], rule['description'], rule['data_source']]
    logging.info(f"\n rule id mapping is \n{rule_id_mapping}\n")
    
    # evaluate the rules one by one as chained
    # start_rule_id = None
    if start_rule_id is None:
        if rule_id_mapping.keys():
            start_rule_id = list(rule_id_mapping.keys())[0]
    
    BR  = BusinessRules(None, [], {})
    file_name = path_leaf(file_path)[:-4] # stripping the .csv
    BR.data_source['master'] = pd.read_csv(file_path)
    
    logging.info(f"\nStart rule id got is {start_rule_id}\n ")
    while start_rule_id != "END":
        # get the rules, next rule id to be evaluated
        rule_to_evaluate, next_if_sucess, next_if_failure, stage, description, data_source = rule_id_mapping[str(start_rule_id)]  
    
        logging.info(f"\nInside the loop \n rule_to_evaluate  {rule_to_evaluate}\n \
                      \nnext_if_sucess {next_if_sucess}\n \
                      \nnext_if_failure {next_if_failure}\n ")
        
        # evaluate the rule
        BR.rules = [json.loads(rule_to_evaluate)] 
        BR.evaluate_business_rules() # apply the business rules
        start_rule_id = next_if_sucess # no matter what go with next if success
        logging.info(f"\n next rule id to execute is {start_rule_id}\n")
        
    logging.info("\n Applied chained rules successfully")
    # finally write to the csv
    writeToCsv(BR.data_source['master'], file_path[:-4]+"_processed.csv")
    return BR



def run_chained_rules(case_id, tenant_id, chain_rules, start_rule_id=None, updated_tables=False, trace_exec=None, rule_params=None):
    """Execute the chained rules"""
    
    # get the mapping of the rules...basically a rule_id maps to a rule
    rule_id_mapping = {}
    for ind, rule in chain_rules.iterrows():
        rule_id_mapping[rule['rule_id']] = [rule['rule_string'], rule['next_if_sucess'], rule['next_if_failure'], rule['stage'], rule['description'], rule['data_source']]
    logging.info(f"\n rule id mapping is \n{rule_id_mapping}\n")
    
    # evaluate the rules one by one as chained
    # start_rule_id = None
    if start_rule_id is None:
        if rule_id_mapping.keys():
            start_rule_id = list(rule_id_mapping.keys())[0]
            trace_exec = []
            rule_params = {}
            
    # if start_rule_id then. coming from other service 
    # get the existing trace and rule params data
    business_rules_db = DB('business_rules', tenant_id=tenant_id, **db_config)
    rule_data_query = "SELECT * from `rule_data` where `case_id`=%s"
    params = [case_id]
    df = business_rules_db.execute(rule_data_query, params=params)
    try:
        trace_exec = json.loads(list(df['trace_data'])[0])
        logging.info(f"\nexistig trace exec is \n{trace_exec}\n")
    except Exception as e:
        logging.info(f"no existing trace data")
        logging.info(f"{str(e)}")
        trace_exec = []
    
    try:
        rule_params = json.loads(list(df['rule_params'])[0])
        logging.info(f"\nexistig rule_params is \n{rule_params}\n")
    except Exception as e:
        logging.info(f"no existing rule params data")
        logging.info(f"{str(e)}")
        rule_params = {}
       
    logging.info(f"\nStart rule id got is {start_rule_id}\n ")
    while start_rule_id != "END":
        # get the rules, next rule id to be evaluated
        rule_to_evaluate, next_if_sucess, next_if_failure, stage, description, data_source = rule_id_mapping[str(start_rule_id)]  
    
        logging.info(f"\nInside the loop \n rule_to_evaluate  {rule_to_evaluate}\n \
                      \nnext_if_sucess {next_if_sucess}\n \
                      \nnext_if_failure {next_if_failure}\n ")
        
        # update the data_table if there is any change
        case_id_data_tables = get_data_sources(tenant_id, case_id, 'case_id_based')
        master_updated_tables = {} 
        if updated_tables:
            master_updated_tables = get_data_sources(tenant_id, case_id, 'updated_tables')
        # consolidate the data into data_tables
        data_tables = {**case_id_data_tables, **master_data_tables, **master_updated_tables} 
        
        # evaluate the rule
        rules = [json.loads(rule_to_evaluate)] 
        BR  = BusinessRules(case_id, rules, data_tables)
        decision = BR.evaluate_rule(rules[0])
        
        logging.info(f"\n got the decision {decision} for the rule id {start_rule_id}")
        logging.info(f"\n updates got are {BR.changed_fields}")
        
        updates = {}
        # update the updates if any
        if BR.changed_fields:
            updates = BR.changed_fields
            update_tables(case_id, tenant_id, updates)

        
        # update the trace_data
        trace_exec.append(start_rule_id)

        logging.info(f"\n params data used from the rules are \n {BR.params_data}\n")
        # update the rule_params
        trace_dict = {
                        str(start_rule_id):{
                            'description' : description if description else 'No description available in the database',
                            'output' : "",
                            'input' : to_DT_data(BR.params_data['input'])
                            }
                        }
        rule_params.update(trace_dict)
        # update the start_rule_id based on the decision
        if decision:
            start_rule_id = next_if_sucess
        else:
            start_rule_id = next_if_failure
        logging.info(f"\n next rule id to execute is {start_rule_id}\n")
        
    
    # off by one updates...
    trace_exec.append(start_rule_id)
    
    # store the trace_exec and rule_params in the database
    update_rule_params_query = f"INSERT INTO `rule_data`(`id`, `case_id`, `rule_params`) VALUES ('NULL',%s,%s) ON DUPLICATE KEY UPDATE `rule_params`=%s"
    params = [case_id, json.dumps(rule_params), json.dumps(rule_params)]
    business_rules_db.execute(update_rule_params_query, params=params)
    
    update_trace_exec_query = f"INSERT INTO `rule_data` (`id`, `case_id`, `trace_data`) VALUES ('NULL',%s,%s) ON DUPLICATE KEY UPDATE `trace_data`=%s"
    params = [case_id, json.dumps(trace_exec), json.dumps(trace_exec)]
    business_rules_db.execute(update_trace_exec_query, params=params)
    
    logging.info("\n Applied chained rules successfully")
    return 'Applied chained rules successfully'

def run_group_rules(case_id, rules, data):
    """Run the rules"""
    rules = [json.loads(rule) for rule in rules] 
    BR  = BusinessRules(case_id, rules, data)
    updates = BR.evaluate_business_rules()
    logging.info(f"\n updates from the group rules are \n{updates}\n")
    return updates

def apply_business_rule(case_id, function_params, tenant_id, file_path):
    """Run the business rules based on the stage in function params and tenant_id
    Args:
        case_id: Unique id that we pass
        function_params: Parameters that we get from the configurations
        tenant_id: Tenant on which we have to apply the rules
    Returns:
    """
    updates = {} # keep a track of updates that are being made by business rules
    try:
        # get the stage from the function_parameters...As of now its first ele..
        # need to make generic or key-value pairs
        logging.info(f"\n case_id {case_id} \nfunction_params {function_params} \ntenant_id {tenant_id}\n")
        stage = function_params['stage'][0]
        
        # no case id passed meaning the operations we are doing on the column wise not case_id wise .
        # feature developed for karvy
        column = False
        if not case_id:
            column = True
            
        # get the rules
        rules = get_rules(tenant_id, stage)
        
        # get the mapping of the rules...basically a rule_id maps to a rule.
        # useful for the chain rule evaluations
        rule_id_mapping = {}
        for ind, rule in rules.iterrows():
            rule_id_mapping[rule['rule_id']] = [rule['rule_string'], rule['next_if_sucess'], rule['next_if_failure'], rule['stage'], rule['description'], rule['data_source']]

        # if columwise processing then run those
        if column:
            output = run_chained_rules_column(file_path, rules)
            return {'flag': True, 'message': 'Applied business rules columnwise successfully.'}

            
        # making it generic takes to take a type parameter from the database..
        # As of now make it (all others  or chained) only
        is_chain_rule = '' not in rule_id_mapping
        
        # get the required table data on which we will be applying business_rules  
        case_id_data_tables = get_data_sources(tenant_id, case_id, 'case_id_based') 
        master_data_tables = get_data_sources(tenant_id, case_id, 'master', master=True)
        
        # consolidate the data into data_tables
        data_tables = {**case_id_data_tables, **master_data_tables} 
        
        logging.info(f"\ndata got from the tables is\n")
        logging.info(data_tables)
        
        updates = {}
        # apply business rules
        if is_chain_rule:
            run_chained_rules(case_id, tenant_id, rules)
        else:
            updates = run_group_rules(case_id, list(rules['rule_string']), data_tables)
            
        # update in the database, the changed fields eventually when all the stage rules were got
        update_tables(case_id, tenant_id, updates)
        
        #  return the updates for viewing
        return {'flag': True, 'message': 'Applied business rules successfully.', 'updates':updates}
    except Exception as e:
        logging.exception('Something went wrong while applying business rules. Check trace.')
        return {'flag': False, 'message': 'Something went wrong while applying business rules. Check logs.', 'error':str(e)}

In [19]:
case_id = None
function_params = {'stage':['cms']}
tenant_id = 'karvy'
file_path = 'C:\\Users\\Algonox\\Desktop\\AlgonoxWork\\BusinessRulesModule\\run_business_rule\\test_cms.csv'
apply_business_rule(case_id, function_params, tenant_id, file_path)

INFO:root:
 case_id None
function_params {'stage': ['cms']}
tenant_id karvy

INFO:root:Host: 3.208.195.34
INFO:root:User: root
INFO:root:Password: AlgoTeam123
INFO:root:Port: 3306
INFO:root:Database: karvy_business_rules
DEBUG:root:Making connection to `karvy_business_rules`...
INFO:root:Engine created for `karvy_business_rules`
INFO:root:Connection established succesfully to `karvy_business_rules`! (3.07 secs to connect)
DEBUG:root:Query: SELECT * from `sequence_rule_data` where `group` = %s
INFO:root:
 rule id mapping is
{'1': ['{"rule_type": "static", "function": "Assign", "parameters": {"assign_table": {"table": "master", "column": "REJECTED"}, "assign_value": {"source": "rule", "value": {"rule_type": "static", "function": "TransformDF", "parameters": {"table": "master", "value1_colomn": {"source": "input", "value": "REJECTED"}, "operator": "broadcast", "value2": {"source": "input", "value": "NO"}}}}}}', '2', '2', '', 'Adding REJECTED colomn and assign NO value.', ''], '2': ['{"rule_type": "static", "function": "Assign", "parameters": {"assign_table": {"table": "master", "column": "Matched"}, "assign_value": {"source": "rule", "value": {"rule_type": "static", "function": "TransformDF", "parameters": {"table": "master", "value1_colomn": {"source": "input", "value": "Matched"}, "operator": "broadcast", "value2": {"source": "input", "value": 0}}}}}}', '3', '3', '', 'Adding Matched Colomn and assigning 0', ''], '3': ['{"rule_type": "static", "function": "Assign", "parameters": {"assign_table": {"table": "master", "column": "ENTRY_AMT"}, "assign_value": {"source": "rule", "value": {"rule_type": "static", "function": "WhereClause", "parameters": {"data_frame": {"source": "rule", "value":\r\n{"rule_type": "static", "function": "TransformDF", "parameters": {"table": "master", "value1_colomn": {"source": "input", "value": "ENTRY_AMT"}, "operator": "*", "value2": {"source": "input", "value": -1}}}}, "from_table": "master", "column": "ENTRY_AMT", "lookup_filters": [{"column_name": "DR_CR", "lookup_operator": "==", "compare_with": {"source": "input", "value": "D"}}]}}}}}', '4', '4', '', "DR_CR Adding '-' to Amount", ''], '4': ['{"rule_type": "static", "function": "Assign", "parameters": {"assign_table": {"table": "master", "column": "CLIENT_CODE"}, "assign_value": {"source": "rule", "value": {"rule_type":\r\n"static", "function": "WhereClause", "parameters": {"data_frame": {"source": "rule", "value": {"rule_type": "static", "function": "TransformDF", "parameters": {"table": "master", "value1_colomn": {"source": "input", "value": "CLIENT_CODE"}, "operator": "broadcast", "value2": {"source": "input", "value": "IO"}}}}, "from_table": "master", "column": "CLIENT_CODE", "lookup_filters": [{"column_name": "CLIENT_CODE", "lookup_operator": "==", "compare_with": {"source": "input", "value": "MAMFIO"}}]}}}}}', 'END', 'END', '', 'Replace MAMFIO as IO', '']}

INFO:root:
Start rule id got is 1

INFO:root:
Inside the loop
 rule_to_evaluate  {"rule_type": "static", "function": "Assign", "parameters": {"assign_table": {"table": "master", "column": "REJECTED"}, "assign_value": {"source": "rule", "value": {"rule_type": "static", "function": "TransformDF", "parameters": {"table": "master", "value1_colomn": {"source": "input", "value": "REJECTED"}, "operator": "broadcast", "value2": {"source": "input", "value": "NO"}}}}}}

next_if_sucess 2

next_if_failure 2

INFO:root:
 Evaluating the rule: {'rule_type': 'static', 'function': 'Assign', 'parameters': {'assign_table': {'table': 'master', 'column': 'REJECTED'}, 'assign_value': {'source': 'rule', 'value': {'rule_type': 'static', 'function': 'TransformDF', 'parameters': {'table': 'master', 'value1_colomn': {'source': 'input', 'value': 'REJECTED'}, 'operator': 'broadcast', 'value2': {'source': 'input', 'value': 'NO'}}}}}}

INFO:root:
Evaluating the rule
{'rule_type': 'static', 'function': 'Assign', 'parameters': {'assign_table': {'table': 'master', 'column': 'REJECTED'}, 'assign_value': {'source': 'rule', 'value': {'rule_type': 'static', 'function': 'TransformDF', 'parameters': {'table': 'master', 'value1_colomn': {'source': 'input', 'value': 'REJECTED'}, 'operator': 'broadcast', 'value2': {'source': 'input', 'value': 'NO'}}}}}}

DEBUG:root:parameters got are {'assign_table': {'table': 'master', 'column': 'REJECTED'}, 'assign_value': {'source': 'rule', 'value': {'rule_type': 'static', 'function': 'TransformDF', 'parameters': {'table': 'master', 'value1_colomn': {'source': 'input', 'value': 'REJECTED'}, 'operator': 'broadcast', 'value2': {'source': 'input', 'value': 'NO'}}}}}
INFO:root:
PARAM OBJECT IS {'source': 'rule', 'value': {'rule_type': 'static', 'function': 'TransformDF', 'parameters': {'table': 'master', 'value1_colomn': {'source': 'input', 'value': 'REJECTED'}, 'operator': 'broadcast', 'value2': {'source': 'input', 'value': 'NO'}}}}

INFO:root:
Evaluating the rule
{'rule_type': 'static', 'function': 'TransformDF', 'parameters': {'table': 'master', 'value1_colomn': {'source': 'input', 'value': 'REJECTED'}, 'operator': 'broadcast', 'value2': {'source': 'input', 'value': 'NO'}}}

INFO:root:parameters got are {'table': 'master', 'value1_colomn': {'source': 'input', 'value': 'REJECTED'}, 'operator': 'broadcast', 'value2': {'source': 'input', 'value': 'NO'}}
INFO:root:
PARAM OBJECT IS {'source': 'input', 'value': 'REJECTED'}

INFO:root:
PARAM OBJECT IS {'source': 'input', 'value': 'NO'}

INFO:root:Updated the data source with the values master REJECTED

INFO:root:updated the changed fields
 changed_fields are {'master': {'REJECTED': 0       NO
1       NO
2       NO
3       NO
4       NO
5       NO
6       NO
7       NO
8       NO
9       NO
10      NO
11      NO
12      NO
13      NO
14      NO
15      NO
16      NO
17      NO
18      NO
19      NO
20      NO
21      NO
22      NO
23      NO
24      NO
25      NO
26      NO
27      NO
28      NO
29      NO
        ..
1516    NO
1517    NO
1518    NO
1519    NO
1520    NO
1521    NO
1522    NO
1523    NO
1524    NO
1525    NO
1526    NO
1527    NO
1528    NO
1529    NO
1530    NO
1531    NO
1532    NO
1533    NO
1534    NO
1535    NO
1536    NO
1537    NO
1538    NO
1539    NO
1540    NO
1541    NO
1542    NO
1543    NO
1544    NO
1545    NO
Length: 1546, dtype: object}}
INFO:root:
 Output: True

INFO:root:
changed fields are
{'master': {'REJECTED': 0       NO
1       NO
2       NO
3       NO
4       NO
5       NO
6       NO
7       NO
8       NO
9       NO
10      NO
11      NO
12      NO
13      NO
14      NO
15      NO
16      NO
17      NO
18      NO
19      NO
20      NO
21      NO
22      NO
23      NO
24      NO
25      NO
26      NO
27      NO
28      NO
29      NO
        ..
1516    NO
1517    NO
1518    NO
1519    NO
1520    NO
1521    NO
1522    NO
1523    NO
1524    NO
1525    NO
1526    NO
1527    NO
1528    NO
1529    NO
1530    NO
1531    NO
1532    NO
1533    NO
1534    NO
1535    NO
1536    NO
1537    NO
1538    NO
1539    NO
1540    NO
1541    NO
1542    NO
1543    NO
1544    NO
1545    NO
Length: 1546, dtype: object}}

INFO:root:
 next rule id to execute is 2

INFO:root:
Inside the loop
 rule_to_evaluate  {"rule_type": "static", "function": "Assign", "parameters": {"assign_table": {"table": "master", "column": "Matched"}, "assign_value": {"source": "rule", "value": {"rule_type": "static", "function": "TransformDF", "parameters": {"table": "master", "value1_colomn": {"source": "input", "value": "Matched"}, "operator": "broadcast", "value2": {"source": "input", "value": 0}}}}}}

next_if_sucess 3

next_if_failure 3

INFO:root:
 Evaluating the rule: {'rule_type': 'static', 'function': 'Assign', 'parameters': {'assign_table': {'table': 'master', 'column': 'Matched'}, 'assign_value': {'source': 'rule', 'value': {'rule_type': 'static', 'function': 'TransformDF', 'parameters': {'table': 'master', 'value1_colomn': {'source': 'input', 'value': 'Matched'}, 'operator': 'broadcast', 'value2': {'source': 'input', 'value': 0}}}}}}

INFO:root:
Evaluating the rule
{'rule_type': 'static', 'function': 'Assign', 'parameters': {'assign_table': {'table': 'master', 'column': 'Matched'}, 'assign_value': {'source': 'rule', 'value': {'rule_type': 'static', 'function': 'TransformDF', 'parameters': {'table': 'master', 'value1_colomn': {'source': 'input', 'value': 'Matched'}, 'operator': 'broadcast', 'value2': {'source': 'input', 'value': 0}}}}}}

DEBUG:root:parameters got are {'assign_table': {'table': 'master', 'column': 'Matched'}, 'assign_value': {'source': 'rule', 'value': {'rule_type': 'static', 'function': 'TransformDF', 'parameters': {'table': 'master', 'value1_colomn': {'source': 'input', 'value': 'Matched'}, 'operator': 'broadcast', 'value2': {'source': 'input', 'value': 0}}}}}
INFO:root:
PARAM OBJECT IS {'source': 'rule', 'value': {'rule_type': 'static', 'function': 'TransformDF', 'parameters': {'table': 'master', 'value1_colomn': {'source': 'input', 'value': 'Matched'}, 'operator': 'broadcast', 'value2': {'source': 'input', 'value': 0}}}}

INFO:root:
Evaluating the rule
{'rule_type': 'static', 'function': 'TransformDF', 'parameters': {'table': 'master', 'value1_colomn': {'source': 'input', 'value': 'Matched'}, 'operator': 'broadcast', 'value2': {'source': 'input', 'value': 0}}}

INFO:root:parameters got are {'table': 'master', 'value1_colomn': {'source': 'input', 'value': 'Matched'}, 'operator': 'broadcast', 'value2': {'source': 'input', 'value': 0}}
INFO:root:
PARAM OBJECT IS {'source': 'input', 'value': 'Matched'}

INFO:root:
PARAM OBJECT IS {'source': 'input', 'value': 0}

INFO:root:Updated the data source with the values master Matched

INFO:root:updated the changed fields
 changed_fields are {'master': {'REJECTED': 0       NO
1       NO
2       NO
3       NO
4       NO
5       NO
6       NO
7       NO
8       NO
9       NO
10      NO
11      NO
12      NO
13      NO
14      NO
15      NO
16      NO
17      NO
18      NO
19      NO
20      NO
21      NO
22      NO
23      NO
24      NO
25      NO
26      NO
27      NO
28      NO
29      NO
        ..
1516    NO
1517    NO
1518    NO
1519    NO
1520    NO
1521    NO
1522    NO
1523    NO
1524    NO
1525    NO
1526    NO
1527    NO
1528    NO
1529    NO
1530    NO
1531    NO
1532    NO
1533    NO
1534    NO
1535    NO
1536    NO
1537    NO
1538    NO
1539    NO
1540    NO
1541    NO
1542    NO
1543    NO
1544    NO
1545    NO
Length: 1546, dtype: object, 'Matched': 0       0
1       0
2       0
3       0
4       0
5       0
6       0
7       0
8       0
9       0
10      0
11      0
12      0
13      0
14      0
15      0
16      0
17      0
18      0
19      0
20      0
21      0
22      0
23      0
24      0
25      0
26      0
27      0
28      0
29      0
       ..
1516    0
1517    0
1518    0
1519    0
1520    0
1521    0
1522    0
1523    0
1524    0
1525    0
1526    0
1527    0
1528    0
1529    0
1530    0
1531    0
1532    0
1533    0
1534    0
1535    0
1536    0
1537    0
1538    0
1539    0
1540    0
1541    0
1542    0
1543    0
1544    0
1545    0
Length: 1546, dtype: int64}}
INFO:root:
 Output: True

INFO:root:
changed fields are
{'master': {'REJECTED': 0       NO
1       NO
2       NO
3       NO
4       NO
5       NO
6       NO
7       NO
8       NO
9       NO
10      NO
11      NO
12      NO
13      NO
14      NO
15      NO
16      NO
17      NO
18      NO
19      NO
20      NO
21      NO
22      NO
23      NO
24      NO
25      NO
26      NO
27      NO
28      NO
29      NO
        ..
1516    NO
1517    NO
1518    NO
1519    NO
1520    NO
1521    NO
1522    NO
1523    NO
1524    NO
1525    NO
1526    NO
1527    NO
1528    NO
1529    NO
1530    NO
1531    NO
1532    NO
1533    NO
1534    NO
1535    NO
1536    NO
1537    NO
1538    NO
1539    NO
1540    NO
1541    NO
1542    NO
1543    NO
1544    NO
1545    NO
Length: 1546, dtype: object, 'Matched': 0       0
1       0
2       0
3       0
4       0
5       0
6       0
7       0
8       0
9       0
10      0
11      0
12      0
13      0
14      0
15      0
16      0
17      0
18      0
19      0
20      0
21      0
22      0
23      0
24      0
25      0
26      0
27      0
28      0
29      0
       ..
1516    0
1517    0
1518    0
1519    0
1520    0
1521    0
1522    0
1523    0
1524    0
1525    0
1526    0
1527    0
1528    0
1529    0
1530    0
1531    0
1532    0
1533    0
1534    0
1535    0
1536    0
1537    0
1538    0
1539    0
1540    0
1541    0
1542    0
1543    0
1544    0
1545    0
Length: 1546, dtype: int64}}

INFO:root:
 next rule id to execute is 3

INFO:root:
Inside the loop
 rule_to_evaluate  {"rule_type": "static", "function": "Assign", "parameters": {"assign_table": {"table": "master", "column": "ENTRY_AMT"}, "assign_value": {"source": "rule", "value": {"rule_type": "static", "function": "WhereClause", "parameters": {"data_frame": {"source": "rule", "value":
{"rule_type": "static", "function": "TransformDF", "parameters": {"table": "master", "value1_colomn": {"source": "input", "value": "ENTRY_AMT"}, "operator": "*", "value2": {"source": "input", "value": -1}}}}, "from_table": "master", "column": "ENTRY_AMT", "lookup_filters": [{"column_name": "DR_CR", "lookup_operator": "==", "compare_with": {"source": "input", "value": "D"}}]}}}}}

next_if_sucess 4

next_if_failure 4

INFO:root:
 Evaluating the rule: {'rule_type': 'static', 'function': 'Assign', 'parameters': {'assign_table': {'table': 'master', 'column': 'ENTRY_AMT'}, 'assign_value': {'source': 'rule', 'value': {'rule_type': 'static', 'function': 'WhereClause', 'parameters': {'data_frame': {'source': 'rule', 'value': {'rule_type': 'static', 'function': 'TransformDF', 'parameters': {'table': 'master', 'value1_colomn': {'source': 'input', 'value': 'ENTRY_AMT'}, 'operator': '*', 'value2': {'source': 'input', 'value': -1}}}}, 'from_table': 'master', 'column': 'ENTRY_AMT', 'lookup_filters': [{'column_name': 'DR_CR', 'lookup_operator': '==', 'compare_with': {'source': 'input', 'value': 'D'}}]}}}}}

INFO:root:
Evaluating the rule
{'rule_type': 'static', 'function': 'Assign', 'parameters': {'assign_table': {'table': 'master', 'column': 'ENTRY_AMT'}, 'assign_value': {'source': 'rule', 'value': {'rule_type': 'static', 'function': 'WhereClause', 'parameters': {'data_frame': {'source': 'rule', 'value': {'rule_type': 'static', 'function': 'TransformDF', 'parameters': {'table': 'master', 'value1_colomn': {'source': 'input', 'value': 'ENTRY_AMT'}, 'operator': '*', 'value2': {'source': 'input', 'value': -1}}}}, 'from_table': 'master', 'column': 'ENTRY_AMT', 'lookup_filters': [{'column_name': 'DR_CR', 'lookup_operator': '==', 'compare_with': {'source': 'input', 'value': 'D'}}]}}}}}

DEBUG:root:parameters got are {'assign_table': {'table': 'master', 'column': 'ENTRY_AMT'}, 'assign_value': {'source': 'rule', 'value': {'rule_type': 'static', 'function': 'WhereClause', 'parameters': {'data_frame': {'source': 'rule', 'value': {'rule_type': 'static', 'function': 'TransformDF', 'parameters': {'table': 'master', 'value1_colomn': {'source': 'input', 'value': 'ENTRY_AMT'}, 'operator': '*', 'value2': {'source': 'input', 'value': -1}}}}, 'from_table': 'master', 'column': 'ENTRY_AMT', 'lookup_filters': [{'column_name': 'DR_CR', 'lookup_operator': '==', 'compare_with': {'source': 'input', 'value': 'D'}}]}}}}
INFO:root:
PARAM OBJECT IS {'source': 'rule', 'value': {'rule_type': 'static', 'function': 'WhereClause', 'parameters': {'data_frame': {'source': 'rule', 'value': {'rule_type': 'static', 'function': 'TransformDF', 'parameters': {'table': 'master', 'value1_colomn': {'source': 'input', 'value': 'ENTRY_AMT'}, 'operator': '*', 'value2': {'source': 'input', 'value': -1}}}}, 'from_table': 'master', 'column': 'ENTRY_AMT', 'lookup_filters': [{'column_name': 'DR_CR', 'lookup_operator': '==', 'compare_with': {'source': 'input', 'value': 'D'}}]}}}

INFO:root:
Evaluating the rule
{'rule_type': 'static', 'function': 'WhereClause', 'parameters': {'data_frame': {'source': 'rule', 'value': {'rule_type': 'static', 'function': 'TransformDF', 'parameters': {'table': 'master', 'value1_colomn': {'source': 'input', 'value': 'ENTRY_AMT'}, 'operator': '*', 'value2': {'source': 'input', 'value': -1}}}}, 'from_table': 'master', 'column': 'ENTRY_AMT', 'lookup_filters': [{'column_name': 'DR_CR', 'lookup_operator': '==', 'compare_with': {'source': 'input', 'value': 'D'}}]}}

INFO:root:parameters got are {'data_frame': {'source': 'rule', 'value': {'rule_type': 'static', 'function': 'TransformDF', 'parameters': {'table': 'master', 'value1_colomn': {'source': 'input', 'value': 'ENTRY_AMT'}, 'operator': '*', 'value2': {'source': 'input', 'value': -1}}}}, 'from_table': 'master', 'column': 'ENTRY_AMT', 'lookup_filters': [{'column_name': 'DR_CR', 'lookup_operator': '==', 'compare_with': {'source': 'input', 'value': 'D'}}]}

INFO:root:
PARAM OBJECT IS {'source': 'input', 'value': 'D'}

INFO:root:
PARAM OBJECT IS {'source': 'rule', 'value': {'rule_type': 'static', 'function': 'TransformDF', 'parameters': {'table': 'master', 'value1_colomn': {'source': 'input', 'value': 'ENTRY_AMT'}, 'operator': '*', 'value2': {'source': 'input', 'value': -1}}}}

INFO:root:
Evaluating the rule
{'rule_type': 'static', 'function': 'TransformDF', 'parameters': {'table': 'master', 'value1_colomn': {'source': 'input', 'value': 'ENTRY_AMT'}, 'operator': '*', 'value2': {'source': 'input', 'value': -1}}}

INFO:root:parameters got are {'table': 'master', 'value1_colomn': {'source': 'input', 'value': 'ENTRY_AMT'}, 'operator': '*', 'value2': {'source': 'input', 'value': -1}}
INFO:root:
PARAM OBJECT IS {'source': 'input', 'value': 'ENTRY_AMT'}

INFO:root:
PARAM OBJECT IS {'source': 'input', 'value': -1}

INFO:root:Updated the data source with the values master ENTRY_AMT

INFO:root:updated the changed fields
 changed_fields are {'master': {'REJECTED': 0       NO
1       NO
2       NO
3       NO
4       NO
5       NO
6       NO
7       NO
8       NO
9       NO
10      NO
11      NO
12      NO
13      NO
14      NO
15      NO
16      NO
17      NO
18      NO
19      NO
20      NO
21      NO
22      NO
23      NO
24      NO
25      NO
26      NO
27      NO
28      NO
29      NO
        ..
1516    NO
1517    NO
1518    NO
1519    NO
1520    NO
1521    NO
1522    NO
1523    NO
1524    NO
1525    NO
1526    NO
1527    NO
1528    NO
1529    NO
1530    NO
1531    NO
1532    NO
1533    NO
1534    NO
1535    NO
1536    NO
1537    NO
1538    NO
1539    NO
1540    NO
1541    NO
1542    NO
1543    NO
1544    NO
1545    NO
Length: 1546, dtype: object, 'Matched': 0       0
1       0
2       0
3       0
4       0
5       0
6       0
7       0
8       0
9       0
10      0
11      0
12      0
13      0
14      0
15      0
16      0
17      0
18      0
19      0
20      0
21      0
22      0
23      0
24      0
25      0
26      0
27      0
28      0
29      0
       ..
1516    0
1517    0
1518    0
1519    0
1520    0
1521    0
1522    0
1523    0
1524    0
1525    0
1526    0
1527    0
1528    0
1529    0
1530    0
1531    0
1532    0
1533    0
1534    0
1535    0
1536    0
1537    0
1538    0
1539    0
1540    0
1541    0
1542    0
1543    0
1544    0
1545    0
Length: 1546, dtype: int64, 'ENTRY_AMT': 0        30000.0
1       199000.0
2         5000.0
3       600000.0
4         1000.0
5         3000.0
6         3000.0
7        25000.0
8         5000.0
9         3000.0
10       20000.0
11       15000.0
12        1000.0
13        5000.0
14        5000.0
15        2500.0
16        2000.0
17        2000.0
18       20000.0
19        5000.0
20       20000.0
21        2000.0
22        1000.0
23       10000.0
24        1000.0
25        2000.0
26      200000.0
27       30000.0
28       50000.0
29       15000.0
          ...
1516      7000.0
1517      2500.0
1518      2000.0
1519     10000.0
1520      3000.0
1521      3000.0
1522      5000.0
1523      5000.0
1524      2000.0
1525      2500.0
1526     60000.0
1527      2500.0
1528     50000.0
1529     10000.0
1530     30000.0
1531      5000.0
1532      5000.0
1533      2000.0
1534     40000.0
1535    400000.0
1536     50000.0
1537      3500.0
1538      1000.0
1539    100000.0
1540     10000.0
1541      3000.0
1542      5000.0
1543      5000.0
1544      7000.0
1545      7000.0
Name: ENTRY_AMT, Length: 1546, dtype: float64}}
INFO:root:
 Output: True

INFO:root:
changed fields are
{'master': {'REJECTED': 0       NO
1       NO
2       NO
3       NO
4       NO
5       NO
6       NO
7       NO
8       NO
9       NO
10      NO
11      NO
12      NO
13      NO
14      NO
15      NO
16      NO
17      NO
18      NO
19      NO
20      NO
21      NO
22      NO
23      NO
24      NO
25      NO
26      NO
27      NO
28      NO
29      NO
        ..
1516    NO
1517    NO
1518    NO
1519    NO
1520    NO
1521    NO
1522    NO
1523    NO
1524    NO
1525    NO
1526    NO
1527    NO
1528    NO
1529    NO
1530    NO
1531    NO
1532    NO
1533    NO
1534    NO
1535    NO
1536    NO
1537    NO
1538    NO
1539    NO
1540    NO
1541    NO
1542    NO
1543    NO
1544    NO
1545    NO
Length: 1546, dtype: object, 'Matched': 0       0
1       0
2       0
3       0
4       0
5       0
6       0
7       0
8       0
9       0
10      0
11      0
12      0
13      0
14      0
15      0
16      0
17      0
18      0
19      0
20      0
21      0
22      0
23      0
24      0
25      0
26      0
27      0
28      0
29      0
       ..
1516    0
1517    0
1518    0
1519    0
1520    0
1521    0
1522    0
1523    0
1524    0
1525    0
1526    0
1527    0
1528    0
1529    0
1530    0
1531    0
1532    0
1533    0
1534    0
1535    0
1536    0
1537    0
1538    0
1539    0
1540    0
1541    0
1542    0
1543    0
1544    0
1545    0
Length: 1546, dtype: int64, 'ENTRY_AMT': 0        30000.0
1       199000.0
2         5000.0
3       600000.0
4         1000.0
5         3000.0
6         3000.0
7        25000.0
8         5000.0
9         3000.0
10       20000.0
11       15000.0
12        1000.0
13        5000.0
14        5000.0
15        2500.0
16        2000.0
17        2000.0
18       20000.0
19        5000.0
20       20000.0
21        2000.0
22        1000.0
23       10000.0
24        1000.0
25        2000.0
26      200000.0
27       30000.0
28       50000.0
29       15000.0
          ...
1516      7000.0
1517      2500.0
1518      2000.0
1519     10000.0
1520      3000.0
1521      3000.0
1522      5000.0
1523      5000.0
1524      2000.0
1525      2500.0
1526     60000.0
1527      2500.0
1528     50000.0
1529     10000.0
1530     30000.0
1531      5000.0
1532      5000.0
1533      2000.0
1534     40000.0
1535    400000.0
1536     50000.0
1537      3500.0
1538      1000.0
1539    100000.0
1540     10000.0
1541      3000.0
1542      5000.0
1543      5000.0
1544      7000.0
1545      7000.0
Name: ENTRY_AMT, Length: 1546, dtype: float64}}

INFO:root:
 next rule id to execute is 4

INFO:root:
Inside the loop
 rule_to_evaluate  {"rule_type": "static", "function": "Assign", "parameters": {"assign_table": {"table": "master", "column": "CLIENT_CODE"}, "assign_value": {"source": "rule", "value": {"rule_type":
"static", "function": "WhereClause", "parameters": {"data_frame": {"source": "rule", "value": {"rule_type": "static", "function": "TransformDF", "parameters": {"table": "master", "value1_colomn": {"source": "input", "value": "CLIENT_CODE"}, "operator": "broadcast", "value2": {"source": "input", "value": "IO"}}}}, "from_table": "master", "column": "CLIENT_CODE", "lookup_filters": [{"column_name": "CLIENT_CODE", "lookup_operator": "==", "compare_with": {"source": "input", "value": "MAMFIO"}}]}}}}}

next_if_sucess END

next_if_failure END

INFO:root:
 Evaluating the rule: {'rule_type': 'static', 'function': 'Assign', 'parameters': {'assign_table': {'table': 'master', 'column': 'CLIENT_CODE'}, 'assign_value': {'source': 'rule', 'value': {'rule_type': 'static', 'function': 'WhereClause', 'parameters': {'data_frame': {'source': 'rule', 'value': {'rule_type': 'static', 'function': 'TransformDF', 'parameters': {'table': 'master', 'value1_colomn': {'source': 'input', 'value': 'CLIENT_CODE'}, 'operator': 'broadcast', 'value2': {'source': 'input', 'value': 'IO'}}}}, 'from_table': 'master', 'column': 'CLIENT_CODE', 'lookup_filters': [{'column_name': 'CLIENT_CODE', 'lookup_operator': '==', 'compare_with': {'source': 'input', 'value': 'MAMFIO'}}]}}}}}

INFO:root:
Evaluating the rule
{'rule_type': 'static', 'function': 'Assign', 'parameters': {'assign_table': {'table': 'master', 'column': 'CLIENT_CODE'}, 'assign_value': {'source': 'rule', 'value': {'rule_type': 'static', 'function': 'WhereClause', 'parameters': {'data_frame': {'source': 'rule', 'value': {'rule_type': 'static', 'function': 'TransformDF', 'parameters': {'table': 'master', 'value1_colomn': {'source': 'input', 'value': 'CLIENT_CODE'}, 'operator': 'broadcast', 'value2': {'source': 'input', 'value': 'IO'}}}}, 'from_table': 'master', 'column': 'CLIENT_CODE', 'lookup_filters': [{'column_name': 'CLIENT_CODE', 'lookup_operator': '==', 'compare_with': {'source': 'input', 'value': 'MAMFIO'}}]}}}}}

DEBUG:root:parameters got are {'assign_table': {'table': 'master', 'column': 'CLIENT_CODE'}, 'assign_value': {'source': 'rule', 'value': {'rule_type': 'static', 'function': 'WhereClause', 'parameters': {'data_frame': {'source': 'rule', 'value': {'rule_type': 'static', 'function': 'TransformDF', 'parameters': {'table': 'master', 'value1_colomn': {'source': 'input', 'value': 'CLIENT_CODE'}, 'operator': 'broadcast', 'value2': {'source': 'input', 'value': 'IO'}}}}, 'from_table': 'master', 'column': 'CLIENT_CODE', 'lookup_filters': [{'column_name': 'CLIENT_CODE', 'lookup_operator': '==', 'compare_with': {'source': 'input', 'value': 'MAMFIO'}}]}}}}
INFO:root:
PARAM OBJECT IS {'source': 'rule', 'value': {'rule_type': 'static', 'function': 'WhereClause', 'parameters': {'data_frame': {'source': 'rule', 'value': {'rule_type': 'static', 'function': 'TransformDF', 'parameters': {'table': 'master', 'value1_colomn': {'source': 'input', 'value': 'CLIENT_CODE'}, 'operator': 'broadcast', 'value2': {'source': 'input', 'value': 'IO'}}}}, 'from_table': 'master', 'column': 'CLIENT_CODE', 'lookup_filters': [{'column_name': 'CLIENT_CODE', 'lookup_operator': '==', 'compare_with': {'source': 'input', 'value': 'MAMFIO'}}]}}}

INFO:root:
Evaluating the rule
{'rule_type': 'static', 'function': 'WhereClause', 'parameters': {'data_frame': {'source': 'rule', 'value': {'rule_type': 'static', 'function': 'TransformDF', 'parameters': {'table': 'master', 'value1_colomn': {'source': 'input', 'value': 'CLIENT_CODE'}, 'operator': 'broadcast', 'value2': {'source': 'input', 'value': 'IO'}}}}, 'from_table': 'master', 'column': 'CLIENT_CODE', 'lookup_filters': [{'column_name': 'CLIENT_CODE', 'lookup_operator': '==', 'compare_with': {'source': 'input', 'value': 'MAMFIO'}}]}}

INFO:root:parameters got are {'data_frame': {'source': 'rule', 'value': {'rule_type': 'static', 'function': 'TransformDF', 'parameters': {'table': 'master', 'value1_colomn': {'source': 'input', 'value': 'CLIENT_CODE'}, 'operator': 'broadcast', 'value2': {'source': 'input', 'value': 'IO'}}}}, 'from_table': 'master', 'column': 'CLIENT_CODE', 'lookup_filters': [{'column_name': 'CLIENT_CODE', 'lookup_operator': '==', 'compare_with': {'source': 'input', 'value': 'MAMFIO'}}]}
INFO:root:
PARAM OBJECT IS {'source': 'input', 'value': 'MAMFIO'}

INFO:root:
PARAM OBJECT IS {'source': 'rule', 'value': {'rule_type': 'static', 'function': 'TransformDF', 'parameters': {'table': 'master', 'value1_colomn': {'source': 'input', 'value': 'CLIENT_CODE'}, 'operator': 'broadcast', 'value2': {'source': 'input', 'value': 'IO'}}}}

INFO:root:
Evaluating the rule
{'rule_type': 'static', 'function': 'TransformDF', 'parameters': {'table': 'master', 'value1_colomn': {'source': 'input', 'value': 'CLIENT_CODE'}, 'operator': 'broadcast', 'value2': {'source': 'input', 'value': 'IO'}}}

INFO:root:parameters got are {'table': 'master', 'value1_colomn': {'source': 'input', 'value': 'CLIENT_CODE'}, 'operator': 'broadcast', 'value2': {'source': 'input', 'value': 'IO'}}
INFO:root:
PARAM OBJECT IS {'source': 'input', 'value': 'CLIENT_CODE'}

INFO:root:
PARAM OBJECT IS {'source': 'input', 'value': 'IO'}

INFO:root:Updated the data source with the values master CLIENT_CODE

INFO:root:updated the changed fields
 changed_fields are {'master': {'REJECTED': 0       NO
1       NO
2       NO
3       NO
4       NO
5       NO
6       NO
7       NO
8       NO
9       NO
10      NO
11      NO
12      NO
13      NO
14      NO
15      NO
16      NO
17      NO
18      NO
19      NO
20      NO
21      NO
22      NO
23      NO
24      NO
25      NO
26      NO
27      NO
28      NO
29      NO
        ..
1516    NO
1517    NO
1518    NO
1519    NO
1520    NO
1521    NO
1522    NO
1523    NO
1524    NO
1525    NO
1526    NO
1527    NO
1528    NO
1529    NO
1530    NO
1531    NO
1532    NO
1533    NO
1534    NO
1535    NO
1536    NO
1537    NO
1538    NO
1539    NO
1540    NO
1541    NO
1542    NO
1543    NO
1544    NO
1545    NO
Length: 1546, dtype: object, 'Matched': 0       0
1       0
2       0
3       0
4       0
5       0
6       0
7       0
8       0
9       0
10      0
11      0
12      0
13      0
14      0
15      0
16      0
17      0
18      0
19      0
20      0
21      0
22      0
23      0
24      0
25      0
26      0
27      0
28      0
29      0
       ..
1516    0
1517    0
1518    0
1519    0
1520    0
1521    0
1522    0
1523    0
1524    0
1525    0
1526    0
1527    0
1528    0
1529    0
1530    0
1531    0
1532    0
1533    0
1534    0
1535    0
1536    0
1537    0
1538    0
1539    0
1540    0
1541    0
1542    0
1543    0
1544    0
1545    0
Length: 1546, dtype: int64, 'ENTRY_AMT': 0        30000.0
1       199000.0
2         5000.0
3       600000.0
4         1000.0
5         3000.0
6         3000.0
7        25000.0
8         5000.0
9         3000.0
10       20000.0
11       15000.0
12        1000.0
13        5000.0
14        5000.0
15        2500.0
16        2000.0
17        2000.0
18       20000.0
19        5000.0
20       20000.0
21        2000.0
22        1000.0
23       10000.0
24        1000.0
25        2000.0
26      200000.0
27       30000.0
28       50000.0
29       15000.0
          ...
1516      7000.0
1517      2500.0
1518      2000.0
1519     10000.0
1520      3000.0
1521      3000.0
1522      5000.0
1523      5000.0
1524      2000.0
1525      2500.0
1526     60000.0
1527      2500.0
1528     50000.0
1529     10000.0
1530     30000.0
1531      5000.0
1532      5000.0
1533      2000.0
1534     40000.0
1535    400000.0
1536     50000.0
1537      3500.0
1538      1000.0
1539    100000.0
1540     10000.0
1541      3000.0
1542      5000.0
1543      5000.0
1544      7000.0
1545      7000.0
Name: ENTRY_AMT, Length: 1546, dtype: float64, 'CLIENT_CODE': 0       MIRAEFNX
1       MIRAEFNX
2       MIRAEFNX
3         MAMFSB
4         MAMFEB
5         MAMFEB
6         MAMFEB
7         MAMFEB
8         MAMFEB
9         MAMFEB
10        MAMFEB
11        MAMFEB
12        MAMFEB
13        MAMFEB
14        MAMFEB
15        MAMFEB
16        MAMFEB
17        MAMFEB
18        MAMFEB
19        MAMFEB
20        MAMFEB
21        MAMFEB
22        MAMFEB
23        MAMFEB
24        MAMFEB
25        MAMFEB
26        MAMFUS
27            IO
28            IO
29            IO
          ...
1516      MAMFTF
1517      MAMFEB
1518      MAMFEB
1519      MAMFEB
1520      MAMFEB
1521      MAMFEB
1522      MAMFEB
1523      MAMFEB
1524      MAMFEB
1525      MAMFEB
1526      MAMFUS
1527          IO
1528          IO
1529          IO
1530          IO
1531          IO
1532          IO
1533          IO
1534          IO
1535      MAMFCM
1536      MAMFTF
1537      MAMFTF
1538      MAMFTF
1539      MAMFFS
1540      MAMFFS
1541      MAMFFS
1542      MAMFFS
1543      MAMFFS
1544          IO
1545          IO
Length: 1546, dtype: object}}
INFO:root:
 Output: True

INFO:root:
changed fields are
{'master': {'REJECTED': 0       NO
1       NO
2       NO
3       NO
4       NO
5       NO
6       NO
7       NO
8       NO
9       NO
10      NO
11      NO
12      NO
13      NO
14      NO
15      NO
16      NO
17      NO
18      NO
19      NO
20      NO
21      NO
22      NO
23      NO
24      NO
25      NO
26      NO
27      NO
28      NO
29      NO
        ..
1516    NO
1517    NO
1518    NO
1519    NO
1520    NO
1521    NO
1522    NO
1523    NO
1524    NO
1525    NO
1526    NO
1527    NO
1528    NO
1529    NO
1530    NO
1531    NO
1532    NO
1533    NO
1534    NO
1535    NO
1536    NO
1537    NO
1538    NO
1539    NO
1540    NO
1541    NO
1542    NO
1543    NO
1544    NO
1545    NO
Length: 1546, dtype: object, 'Matched': 0       0
1       0
2       0
3       0
4       0
5       0
6       0
7       0
8       0
9       0
10      0
11      0
12      0
13      0
14      0
15      0
16      0
17      0
18      0
19      0
20      0
21      0
22      0
23      0
24      0
25      0
26      0
27      0
28      0
29      0
       ..
1516    0
1517    0
1518    0
1519    0
1520    0
1521    0
1522    0
1523    0
1524    0
1525    0
1526    0
1527    0
1528    0
1529    0
1530    0
1531    0
1532    0
1533    0
1534    0
1535    0
1536    0
1537    0
1538    0
1539    0
1540    0
1541    0
1542    0
1543    0
1544    0
1545    0
Length: 1546, dtype: int64, 'ENTRY_AMT': 0        30000.0
1       199000.0
2         5000.0
3       600000.0
4         1000.0
5         3000.0
6         3000.0
7        25000.0
8         5000.0
9         3000.0
10       20000.0
11       15000.0
12        1000.0
13        5000.0
14        5000.0
15        2500.0
16        2000.0
17        2000.0
18       20000.0
19        5000.0
20       20000.0
21        2000.0
22        1000.0
23       10000.0
24        1000.0
25        2000.0
26      200000.0
27       30000.0
28       50000.0
29       15000.0
          ...
1516      7000.0
1517      2500.0
1518      2000.0
1519     10000.0
1520      3000.0
1521      3000.0
1522      5000.0
1523      5000.0
1524      2000.0
1525      2500.0
1526     60000.0
1527      2500.0
1528     50000.0
1529     10000.0
1530     30000.0
1531      5000.0
1532      5000.0
1533      2000.0
1534     40000.0
1535    400000.0
1536     50000.0
1537      3500.0
1538      1000.0
1539    100000.0
1540     10000.0
1541      3000.0
1542      5000.0
1543      5000.0
1544      7000.0
1545      7000.0
Name: ENTRY_AMT, Length: 1546, dtype: float64, 'CLIENT_CODE': 0       MIRAEFNX
1       MIRAEFNX
2       MIRAEFNX
3         MAMFSB
4         MAMFEB
5         MAMFEB
6         MAMFEB
7         MAMFEB
8         MAMFEB
9         MAMFEB
10        MAMFEB
11        MAMFEB
12        MAMFEB
13        MAMFEB
14        MAMFEB
15        MAMFEB
16        MAMFEB
17        MAMFEB
18        MAMFEB
19        MAMFEB
20        MAMFEB
21        MAMFEB
22        MAMFEB
23        MAMFEB
24        MAMFEB
25        MAMFEB
26        MAMFUS
27            IO
28            IO
29            IO
          ...
1516      MAMFTF
1517      MAMFEB
1518      MAMFEB
1519      MAMFEB
1520      MAMFEB
1521      MAMFEB
1522      MAMFEB
1523      MAMFEB
1524      MAMFEB
1525      MAMFEB
1526      MAMFUS
1527          IO
1528          IO
1529          IO
1530          IO
1531          IO
1532          IO
1533          IO
1534          IO
1535      MAMFCM
1536      MAMFTF
1537      MAMFTF
1538      MAMFTF
1539      MAMFFS
1540      MAMFFS
1541      MAMFFS
1542      MAMFFS
1543      MAMFFS
1544          IO
1545          IO
Length: 1546, dtype: object}}

INFO:root:
 next rule id to execute is END

INFO:root:
 Applied chained rules successfully

{'flag': True, 'message': 'Applied business rules columnwise successfully.'}

In [9]:
a = {1:2}

In [10]:
b = {3:4}

In [16]:
c = {}

In [18]:
c.update(a)
c.update(b)
c

{3: 4, 1: 2}

In [1]:
sample_rule = {"rule_type": "static", "function": "Assign", "parameters": {"assign_table": {"table": "ocr", "column": "Amount"}, "assign_value": {"source": "rule", "value": {"rule_type": "static", "function": "WhereClause", "parameters": {"data_frame": {"source": "rule", "value": {"rule_type": "static", "function": "TransformDF", "parameters": {"table": "ocr", "value1_colomn": {"source": "input", "value": "Amount"}, "operator": "*", "value2": {"source":
"input", "value": -1}}}}, "from_table": "ocr", "colomn": "Amount", "lookup_filters": [{"column_name": "DR_CR",
"lookup_operator": "==", "compare_with": {"source": "input", "value": "D"}}]}}}}}

In [3]:
list_to_change = ['DR_CR', 'STATUS', 'REJECTED']
for change in list_to_change:
    sample_rule['parameters']['assign_table']['column'] = change
    print ('\n')
    print (sample_rule)
    print ('\n')

{'rule_type': 'static', 'function': 'Assign', 'parameters': {'assign_table': {'table': 'ocr', 'column': 'DR_CR'}, 'assign_value': {'source': 'rule', 'value': {'rule_type': 'static', 'function': 'WhereClause', 'parameters': {'data_frame': {'source': 'rule', 'value': {'rule_type': 'static', 'function': 'TransformDF', 'parameters': {'table': 'ocr', 'value1_colomn': {'source': 'input', 'value': 'Amount'}, 'operator': '*', 'value2': {'source': 'input', 'value': -1}}}}, 'from_table': 'ocr', 'colomn': 'Amount', 'lookup_filters': [{'column_name': 'DR_CR', 'lookup_operator': '==', 'compare_with': {'source': 'input', 'value': 'D'}}]}}}}}




{'rule_type': 'static', 'function': 'Assign', 'parameters': {'assign_table': {'table': 'ocr', 'column': 'STATUS'}, 'assign_value': {'source': 'rule', 'value': {'rule_type': 'static', 'function': 'WhereClause', 'parameters': {'data_frame': {'source': 'rule', 'value': {'rule_type': 'static', 'function': 'TransformDF', 'parameters': {'table': 'ocr', 'value1_colomn': {'source': 'input', 'value': 'Amount'}, 'operator': '*', 'value2': {'source': 'input', 'value': -1}}}}, 'from_table': 'ocr', 'colomn': 'Amount', 'lookup_filters': [{'column_name': 'DR_CR', 'lookup_operator': '==', 'compare_with': {'source': 'input', 'value': 'D'}}]}}}}}




{'rule_type': 'static', 'function': 'Assign', 'parameters': {'assign_table': {'table': 'ocr', 'column': 'REJECTED'}, 'assign_value': {'source': 'rule', 'value': {'rule_type': 'static', 'function': 'WhereClause', 'parameters': {'data_frame': {'source': 'rule', 'value': {'rule_type': 'static', 'function': 'TransformDF', 'parameters': {'table': 'ocr', 'value1_colomn': {'source': 'input', 'value': 'Amount'}, 'operator': '*', 'value2': {'source': 'input', 'value': -1}}}}, 'from_table': 'ocr', 'colomn': 'Amount', 'lookup_filters': [{'column_name': 'DR_CR', 'lookup_operator': '==', 'compare_with': {'source': 'input', 'value': 'D'}}]}}}}}